### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by achukhrov-ffr-team** [ivanDonadello/Food-Categories-Classification#1]
Could you please publish your trained model?
Or please send it to me by email?
My email is: kurbobo@yandex.ru

**Comment by achukhrov-ffr-team** [comment]
![image](https://user-images.githubusercontent.com/78736624/115022373-f6b90a80-9ec5-11eb-86d7-a6d8f2f0a16a.png)
I can't get access to download the pretrained model:(

**Comment by ivanDonadello** [comment]
Dear @achukhrov-ffr-team thanks for the interest in the models. My ex institution has changed the permissions, so I am trying to retrieve these models and made them public again. I'll let you know when they will be available.

**Comment by ivanDonadello** [comment]
Thanks for the patience

**Comment by achukhrov-ffr-team** [comment]
Thank you!

**Comment by ivanDonadello** [comment]
@achukhrov-ffr-team models and data recovered!
