### ISSUE TITLE
Link to pre-trained models results in `...link has expired...` error

### ISSUE THREAD

**Issue by thearod5** [ivanDonadello/Food-Categories-Classification#2]
The `readme.md` inside of `/models` contains a link to the pre-trained models which results in the error described in the title.

**Comment by ivanDonadello** [comment]
Dear Alberto,

now the link should work.

Best
Ivan

Il giorno sab 23 apr 2022 alle ore 20:04 Alberto Daniel Rodriguez <
***@***.***> ha scritto:

**Comment by sakshamgarg** [comment]
Hi

I was trying to access the pre-trained model. I am getting the same error and not able to access link. Can you please help me get the link as well.

**Comment by ivanDonadello** [comment]
Dear @sakshamgarg 

the link should work now. Sorry for the annoyance.

Best

Ivan
